#!/bin/python3

import os


def decrypt_password(s):
    tmp = list(s)

    for i, c in enumerate(tmp):
        if c == '*':
            tmp[i - 1], tmp[i - 2] = tmp[i - 2], tmp[i - 1]
            del tmp[i]

    pad = 1
    for i, c in enumerate(reversed(tmp)):
        if c == '0':
            tmp[len(tmp) - pad - i] = tmp[0]
            del tmp[0]
            pad -= 1

    return ''.join(tmp)


def main():
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = decrypt_password(s)

    fptr.write(result + '\n')

    fptr.close()


if __name__ == '__main__':
    main()
